### PR TITLE
GCP Backend

### PR DESCRIPTION
**Pull request by ric-evans**
closes https://github.com/WIPACrepo/MQClient/issues/6

In short, implement a GCP backend.

Other things done:
- moved `message_generator()` acking/nacking logic to `MessageGeneratorContext` manager
- added more common logging
- added `_to_message()` to all backend interfaces
  + helper functions for mapping to common `Message` interface/instance
- added `serialize_data()` and `deserialize_data()` to `Message`
  + this also makes it possible in the future to change the serialization protocol (currently pickle)
- added custom Exceptions for potential user-visible errors
- made common config for retry attempts (as possible)
- moved timeout to `Queue` instance-level
- removed configurable auto-nacking/acking (always auto ack/nack)
- split up the CircleCI "integrate" job
- made room for future dev with multiple-subscription model in Pulsar and GCP

### CODE REVIEW

**Comment by ric-evans** [comment]
@dsschult Without diving into the details, there are settings to turn off auto message-acking/nacking in the `Queue` API. That's been here from before I took over this project. And I think it's a feature we should keep. HOWEVER, there's never been a way to manually ack/nack a message because `Queue` returns the message data, not the `Message` instance. We could instead return a `Message` instance, though this seems unnecessary for 90% of use cases. What are your thoughts here?

**Comment by dsschult** [comment]
> @dsschult Without diving into the details, there are settings to turn off auto message-acking/nacking in the `Queue` API. That's been here from before I took over this project. And I think it's a feature we should keep. HOWEVER, there's never been a way to manually ack/nack a message because `Queue` returns the message data, not the `Message` instance. We could instead return a `Message` instance, though this introduces an extra unnecessary step for 90% of use cases. What are your thoughts here?

I think in the beginning when you called `recv_one` it would give you the message or save it somehow, so manual ack/nack would work.  Now that we've switched it to a context manager and can catch an exception, that's no longer required.  So I'm in favor of removing it from the high-level interface.

**Comment by ric-evans** [comment]
> > @dsschult Without diving into the details, there are settings to turn off auto message-acking/nacking in the `Queue` API. That's been here from before I took over this project. And I think it's a feature we should keep. HOWEVER, there's never been a way to manually ack/nack a message because `Queue` returns the message data, not the `Message` instance. We could instead return a `Message` instance, though this introduces an extra unnecessary step for 90% of use cases. What are your thoughts here?
> 
> I think in the beginning when you called `recv_one` it would give you the message or save it somehow, so manual ack/nack would work. Now that we've switched it to a context manager and can catch an exception, that's no longer required. So I'm in favor of removing it from the high-level interface.

That works for nacking. The consumer would need to raise an Exception inside the context. So no harm there. But GCP has a setting where it auto-nacks after x seconds. And I can see a scenario where each iteration would take long enough that a message could be nacked then redelivered. GCP's max wait time is 10 minutes. If we want to allow longer than that, a manual ack would be useful.

**Comment by dsschult** [comment]
> > > @dsschult Without diving into the details, there are settings to turn off auto message-acking/nacking in the `Queue` API. That's been here from before I took over this project. And I think it's a feature we should keep. HOWEVER, there's never been a way to manually ack/nack a message because `Queue` returns the message data, not the `Message` instance. We could instead return a `Message` instance, though this introduces an extra unnecessary step for 90% of use cases. What are your thoughts here?
> > 
> > 
> > I think in the beginning when you called `recv_one` it would give you the message or save it somehow, so manual ack/nack would work. Now that we've switched it to a context manager and can catch an exception, that's no longer required. So I'm in favor of removing it from the high-level interface.
> 
> That works for nacking. The consumer would need to raise an Exception inside the context. So no harm there. But GCP has a setting where it auto-nacks after x seconds. And I can see a scenario where each iteration would take long enough that a message could be nacked then redelivered. GCP's max wait time is 10 minutes. If we want to allow longer than that, a manual ack would be useful.

I think we can leave it at that, and just document that GCP only works <10 minutes for the high-level interface.

**Comment by ric-evans** [comment]
Note: This uses GCP 1.7.0, I'm in the process of converting this to 2.6.1. The biggest breaking differences are syntactical.

**Review by dsschult — APPROVED** [review]
This generally looks good to me.  I did skim some of the changes, so if there's anything in particular you have questions about, point me to them.

**Comment by ric-evans** [comment]
> This generally looks good to me. I did skim some of the changes, so if there's anything in particular you have questions about, point me to them.

If nothing stood out to you, then that's a good thing!

**Pull request merged**
